Documents/wdadiii_groep08/RetailBackoffice/App.Web/Areas/Admin/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace App.Web.Areas.Admin.Controllers
{
    public class CommentController : AdminController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(Int64 id)
        {
            try
            {
                var model = this.UnitOfWork.EntityCommentRepository.GetByID(id);
                if (model == null)
                    throw new Exception();

                this.UnitOfWork.EntityCommentRepository.Delete(id);
                this.UnitOfWork.Save(); 
                
                var message = String.Format("Deleted the comment with id '{0}' from the database!", model.Id);
                return Json(new { state = 1, id = model.Id, message = message });
            }
            catch
            {
                var message = String.Format("Could not delete the comment with id '{0}' from the database!", id);
                return Json(new { state = 0, id = id, message = message });
            }
        }

        [HttpPost]
        public ActionResult VirtualDelete(Int64 id)
        {
            try
            {
                var model = this.UnitOfWork.EntityCommentRepository.GetByID(id);
                if (model == null)
                    throw new Exception();

                model.DeletedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;

                this.UnitOfWork.EntityCommentRepository.Update(model);
                this.UnitOfWork.Save();

                var message = String.Format("Virtual deleted the comment with id '{0}' from the database!", model.Id);
                return Json(new { state = 1, id = model.Id, message = message });
            }
            catch
            {
                var message = String.Format("Could not virtual delete the comment with id '{0}' from the database!", id);
                return Json(new { state = 0, id = id, message = message });
            }
        }

        [HttpPost]
        public ActionResult VirtualUnDelete(Int64 id)
        {
            try
            {
                var model = this.UnitOfWork.EntityCommentRepository.GetByID(id);
                if (model == null)
                    throw new Exception();

                model.DeletedDate = null;
                model.ModifiedDate = DateTime.Now;

                this.UnitOfWork.EntityCommentRepository.Update(model);
                this.UnitOfWork.Save();

                var message = String.Format("Virtual undeleted the comment with id '{0}' from the database!", model.Id);
                return Json(new { state = 1, id = model.Id, message = message });
            }
            catch
            {
                var message = String.Format("Could not virtual undelete the comment with id '{0}' from the database!", id);
                return Json(new { state = 0, id = id, message = message });
            }
        }

        [HttpPost]
        public ActionResult Lock(Int64 id)
        {
            try
            {
                var model = this.UnitOfWork.EntityCommentRepository.GetByID(id);
                if (model == null)
                    throw new Exception();

                model.LockedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;

                this.UnitOfWork.EntityCommentRepository.Update(model);
                this.UnitOfWork.Save();

                var message = String.Format("Locked the comment with id '{0}' from the database!", model.Id);
                return Json(new { state = 1, id = model.Id, message = message });
            }
            catch
            {
                var message = String.Format("Could not lock the comment with id '{0}' from the database!", id);
                return Json(new { state = 0, id = id, message = message });
            }
        }

        [HttpPost]
        public ActionResult UnLock(Int64 id)
        {
            try
            {
                var model = this.UnitOfWork.EntityCommentRepository.GetByID(id);
                if (model == null)
                    throw new Exception();

                model.LockedDate = null;
                model.ModifiedDate = DateTime.Now;

                this.UnitOfWork.EntityCommentRepository.Update(model);
                this.UnitOfWork.Save();

                var message = String.Format("UnLocked the comment with id '{0}' from the database!", model.Id);
                return Json(new { state = 1, id = model.Id, message = message });
            }
            catch
            {
                var message = String.Format("Could not unlock the comment with id '{0}' from the database!", id);
                return Json(new { state = 0, id = id, message = message });
            }
        }

        public ActionResult PVCommentsList(string sort, string direction, string filter, int? page)
        {
            var pageNumber = page ?? 1;
            var tempSort = String.IsNullOrEmpty(sort) ? "" : sort;
            var tempDirection = String.IsNullOrEmpty(direction) ? "asc" : direction;
            var tempFilter = String.IsNullOrEmpty(filter) ? "" : filter;

            ViewBag.Sort = tempSort;
            ViewBag.Direction = tempDirection;
            ViewBag.Filter = tempFilter;

            var model = this.UnitOfWork.EntityCommentRepository.Get(
                filter:
                c => c.User.UserName.Contains(tempFilter)
                );

            if (!String.IsNullOrEmpty(sort))
            {
                switch (sort)
                {
                    case "sender":
                        if (direction == "asc")
                            model.OrderBy(c => c.User.UserName).ThenByDescending(c => c.CreatedDate).ThenByDescending(c => c.ModifiedDate);
                        else
                            model.OrderByDescending(c => c.User.UserName).ThenByDescending(c => c.CreatedDate).ThenByDescending(c => c.ModifiedDate);
                        break;
                }
            }
            else
            {
                model.OrderByDescending(c => c.CreatedDate).ThenByDescending(c => c.ModifiedDate);
            }

            var pagedModel = model.ToPagedList(pageNumber, 10);

            return PartialView("_CommentsListPartial", pagedModel);
        }

    }
}

Documents/wdadiii_groep08/RetailBackoffice/App.Web/Areas/Admin/Views/Comment/Index.cshtml
@{
    ViewBag.Title = "Bid Management";
    ViewBag.SubTitle = "Overview";
    ViewBag.Description = "In this view you can manage the bids made by users.";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPage.cshtml";
}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="comments-list">
        @{Html.RenderAction("PVCommentsList", "Comment", new { area = "Admin" });}
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

Documents/wdadiii_groep08/RetailBackoffice/App.Web/Areas/Admin/Views/Comment/_CommentsListPartial.cshtml
@model PagedList.IPagedList<App.Models.EntityComment>
@using PagedList.Mvc;

<div class="panel panel-default">
    <div class="pandel-body">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Sender</th>
                        <th>Receiver</th>
                        <th>Bid</th>
                        <th>Bid placed</th>
                        <th>Reactions on bid</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var comment in Model)
                    {
                        <tr data-id="comment-@comment.Id" data-title="@comment.Id" data-update-target="#comments-list" data-update-href="/Admin/Comment/PVCommentsList" >
                            <td>
                                @comment.User.UserName
                            </td>
                            <td>
                                @if (comment.ParentComment != null)
                                {
                                    <text>@comment.ParentComment.User.UserName</text>
                                }else{
                                    <text>Bid on article: @comment.EntityId</text>   
                                }
                            </td>
                            <td>
                                @Html.Raw(@comment.Body + " euro")
                            </td>
                            <td>@comment.CreatedDate</td>
                            <td><span class="badge">@comment.ChildComments.Count</span></td>
                            <td>
                                @if (comment.LockedDate != null)
                                {
                                    <a href="@Url.Action("UnLock", new {id=@comment.Id})" title="Unlock comment: @comment.Id" class="confirm-link" data-cat="comment" data-id="@comment.Id" data-action="unlock"><i class="fa fa-unlock"></i></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("Lock", new { id = @comment.Id })" title="Lock comment: @comment.Id" class="confirm-link" data-cat="comment" data-id="@comment.Id" data-action="lock"><i class="fa fa-lock"></i></a>
                                }
                                @if (comment.DeletedDate != null)
                                {
                                    <a href="@Url.Action("VirtualUnDelete", new {id=@comment.Id})" title="Undelete comment: @comment.Id" class="confirm-link" data-cat="comment" data-id="@comment.Id" data-action="virtualundelete"><i class="fa fa-eye"></i></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("VirtualDelete", new { id = @comment.Id })" title="Virtual delete comment: @comment.Id" class="confirm-link" data-cat="comment" data-id="@comment.Id" data-action="virtualdelete"><i class="fa fa-eye-slash"></i></a>
                                }
                                <a href="@Url.Action("Delete", new {id=@comment.Id})" title="Delete comment: @comment.Id" class="confirm-link" data-cat="comment" data-id="@comment.Id" data-action="delete"><i class="fa fa-eraser"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>            
        </div>
        <div class="panel-footer">
            @Html.PagedListPager(Model, page => Url.Action("PVCommentsList", new {page = page, filter = ViewBag.Filter}), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions(){HttpMethod="GET", UpdateTargetId="comments-list", OnComplete="PagedOnComplete"}))
        </div>
    </div>
</div>
<script>
    function PagedOnComplete(ev) {
        setupConfirmDialog();
    }
</script>